'use client';

import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { CheckCircle2, ShieldAlert } from 'lucide-react';
import type { RoundtableConsensus, ValidatorResult } from '@hermes/shared';
import { cn } from '@/lib/cn';

export function ConsensusCard({ consensus, validator }: { consensus: RoundtableConsensus; validator?: ValidatorResult | null }) {
  const scores = validator?.scores;
  return <div className="space-y-5 rounded-lg border-2 border-amber-300 bg-amber-50/60 p-5 dark:border-amber-800 dark:bg-amber-950/20"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-amber-600" /><h2 className="font-semibold">Consensus reached</h2><span className="ml-auto text-xs text-zinc-500">{consensus.rounds} rounds</span></div><div className="prose prose-sm max-w-none dark:prose-invert"><ReactMarkdown remarkPlugins={[remarkGfm]}>{consensus.finalAnswer}</ReactMarkdown></div>{consensus.tasks?.length ? <div className="overflow-x-auto"><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">Execution tasks</h3><table className="w-full min-w-[42rem] text-left text-xs"><thead className="text-zinc-500"><tr><th className="pb-2 pr-3">Agent</th><th className="pb-2 pr-3">Target</th><th className="pb-2 pr-3">Input</th><th className="pb-2">Expected output</th></tr></thead><tbody>{consensus.tasks.map((task, index) => <tr key={`${task.agent}-${index}`} className="border-t border-amber-200 dark:border-amber-900"><td className="py-2 pr-3 font-medium capitalize">{task.agent}</td><td className="py-2 pr-3">{task.target}</td><td className="py-2 pr-3">{task.input}</td><td className="py-2">{task.expectedOutput}</td></tr>)}</tbody></table></div> : null}<div className="grid gap-4 md:grid-cols-2"><div><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">Agreements</h3><ul className="space-y-1 text-sm">{consensus.agreements.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</li>)}</ul></div><div><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">Disagreements / risks</h3><ul className="space-y-1 text-sm">{(consensus.risks ?? consensus.disagreements).map((item) => <li key={item} className="flex gap-2"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />{item}</li>)}</ul></div></div>{scores && <div><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Validator</h3><span className={cn('text-xs font-semibold', validator?.pass ? 'text-emerald-600' : 'text-red-600')}>{validator?.pass ? 'Pass' : 'Review required'}</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(scores).map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-[11px] capitalize text-zinc-500"><span>{label}</span><span>{value}/100</span></div><div className="h-1.5 rounded-full bg-amber-200 dark:bg-amber-900"><div className="h-full rounded-full bg-amber-600" style={{ width: `${value}%` }} /></div></div>)}</div></div>}</div>;
}
